sudo: true
cache: false

env:
- URL=https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz

before_install:
- openssl aes-256-cbc -K $encrypted_79a2f6093848_key -iv $encrypted_79a2f6093848_iv
  -in assets/server.key.enc -out assets/server.key -d
- export SFDX_LOG_LEVEL=DEBUG
- mkdir sfdx
- wget $URL
- tar xJf sfdx-linux-amd64.tar.xz -C sfdx --strip-components 1
- "./sfdx/install"
- sfdx --version
- sfdx plugins --core
- sfdx plugins
- sfdx force --help
- sfdx commands
- sfdx force:auth:jwt:grant --clientid $CONSUMERKEY --jwtkeyfile $SERVERKEY --username $USERNAME --setdefaultdevhubusername -a HubOrg

script:
- sfdx force:org:create -v HubOrg -s -f config/project-scratch-def.json -a Scratchorg --wait 3
- sfdx force:org:display -u Scratchorg
- sfdx force:source:push -u Scratchorg
- sfdx force:apex:test:run -u Scratchorg --wait 10
- sfdx force:org:delete -u Scratchorg -p


